# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The broswer title of the blog post.', max_length=255)),
                ('slug', models.CharField(help_text='The path of the blog post.', max_length=255)),
                ('meta_author', models.TextField(blank=True, help_text='The author meta tag contents, if blank tag will not display.', null=True)),
                ('meta_description', models.TextField(blank=True, help_text='The description meta tag contents, if blank tag will not display.', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='The keywords meta tag contents, if blank tag will not display.', null=True)),
                ('content', models.TextField(blank=True, default='', help_text='The html content of the blog post.')),
            ],
        ),
    ]
