# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20170326_1623'),
        ('snippets', '0002_remove_snippet_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='menu_item',
            field=models.ManyToManyField(to='menu.MenuItem'),
        ),
    ]
