# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(default=1, help_text='The path of the page.', max_length=255),
            preserve_default=False,
        ),
    ]
