# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='The broswer title of the page.', max_length=255),
        ),
    ]
