# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.CharField(default=1, help_text='This is an internal refernce to select the menu.', max_length=255),
            preserve_default=False,
        ),
    ]
