# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170326_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='not_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
